In [1]:
# Loading Packages
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
from sklearn.datasets impo                                                                                                                                                                          rt fetch_20newsgroups
from pprint import pprint
import pandas as pd

In [5]:
fetch_20newsgroups

<function sklearn.datasets.twenty_newsgroups.fetch_20newsgroups>

In [2]:
# Importing both train and test data
X_train =  pd.DataFrame(fetch_20newsgroups(shuffle=True, random_state=1,subset="train",
                             remove=('headers', 'footers', 'quotes')).data)
X_test = pd.DataFrame(fetch_20newsgroups(shuffle=True, random_state=1,subset="test",
                             remove=('headers', 'footers', 'quotes')).data)

In [44]:
# Displaying the different topics of train data
topics = fetch_20newsgroups(subset="train")
topics.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [42]:
# Displaying the first 5 rows
X_train.head()

0
0  Well i'm not sure about the story nad it did s...
1  \n\n\n\n\n\n\nYeah, do you expect people to re...
2  Although I realize that principle is not one o...
3  Notwithstanding all the legitimate fuss about ...
4  Well, I will have to change the scoring on my ...

In [7]:
# Tf-idf
vectorizer = TfidfVectorizer(max_df = 0.5,
                             use_idf=True, 
                             smooth_idf=True)

In [8]:
# SVD
from sklearn.decomposition import TruncatedSVD
svd_model = TruncatedSVD(n_components=500, 
                         algorithm='randomized',
                         n_iter=10, random_state=42)


In [23]:
# Building the pipeline
from sklearn.pipeline import Pipeline
svd_transformer = Pipeline([('tfidf', vectorizer), 
                            ('svd', svd_model)])
preprocessing_model = svd_transformer.fit(X_train[0])
svd_matrix_train = preprocessing_model.transform(X_train[0])

In [46]:
svd_matrix_train.shape

(11314, 500)

In [17]:
vectorizer.vocabulary_

{'well': 96210,
 'not': 66506,
 'sure': 86572,
 'about': 16251,
 'story': 85586,
 'nad': 64863,
 'did': 33550,
 'seem': 81417,
 'biased': 22687,
 'what': 96382,
 'disagree': 33847,
 'with': 96908,
 'your': 100212,
 'statement': 85167,
 'media': 60687,
 'out': 68841,
 'ruin': 79540,
 'israels': 51265,
 'reputation': 77648,
 'rediculous': 76799,
 'most': 63210,
 'pro': 73273,
 'israeli': 51257,
 'world': 97276,
 'having': 45893,
 'lived': 57007,
 'europe': 38172,
 'realize': 76457,
 'incidences': 49521,
 'such': 86156,
 'as': 19755,
 'one': 68096,
 'described': 33046,
 'letter': 56320,
 'have': 45883,
 'occured': 67518,
 'whole': 96530,
 'try': 90407,
 'ignore': 48824,
 'them': 88570,
 'subsidizing': 86047,
 'existance': 38623,
 'europeans': 38174,
 'are': 19442,
 'at': 20122,
 'least': 56043,
 'same': 80363,
 'degree': 32592,
 'so': 83660,
 'think': 88727,
 'might': 61676,
 'be': 21986,
 'reason': 76503,
 'they': 88686,
 'report': 77563,
 'more': 63104,
 'clearly': 27820,
 'on': 68074,


In [60]:
# Querying a document related to one of the document in test data
query = preprocessing_model.transform(X_test.iloc[2])

In [61]:
query.shape

(1, 500)

In [63]:
# Calculating cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
distance_matrix = cosine_similarity(svd_matrix_train,query)

In [64]:
cosine_similarity

<function sklearn.metrics.pairwise.cosine_similarity>

In [65]:
distance_matrix.shape

(11314, 1)

In [59]:
print(distance_matrix)

[[ 0.18959809]
 [ 0.1253668 ]
 [ 0.10674555]
 ..., 
 [ 0.06834267]
 [ 0.1360393 ]
 [ 0.23134401]]


In [96]:
a = np.random.rand(10)
a

array([ 0.94663653,  0.44345842,  0.42029067,  0.16104716,  0.99863645,
        0.69255612,  0.55712361,  0.18674284,  0.46841015,  0.40545377])

In [97]:
np.sort(a)

array([ 0.16104716,  0.18674284,  0.40545377,  0.42029067,  0.44345842,
        0.46841015,  0.55712361,  0.69255612,  0.94663653,  0.99863645])

In [101]:
xx=a[np.argpartition(a,-5)[-5:]]
xx

array([ 0.46841015,  0.55712361,  0.69255612,  0.94663653,  0.99863645])

In [104]:
np.argsort(a)

array([3, 7, 9, 2, 1, 8, 6, 5, 0, 4])

In [38]:
# Function to return indices of top n elemets
def largest_indices(ary, n):
    """Returns the n largest indices from a numpy array."""
    flat = ary.flatten()
    indices = np.argpartition(flat, -n)[-n:]
    indices = indices[np.argsort(-flat[indices])]
    return np.unravel_index(indices, ary.shape)

In [39]:
largest_indices(distance_matrix,5)

(array([ 7731, 10285,  4931,  8474, 10460]), array([0, 0, 0, 0, 0]))

In [40]:
X_train[0][2]

"Although I realize that principle is not one of your strongest\npoints, I would still like to know why do do not ask any question\nof this sort about the Arab countries.\n\n   If you want to continue this think tank charade of yours, your\nfixation on Israel must stop.  You might have to start asking the\nsame sort of questions of Arab countries as well.  You realize it\nwould not work, as the Arab countries' treatment of Jews over the\nlast several decades is so bad that your fixation on Israel would\nbegin to look like the biased attack that it is.\n\n   Everyone in this group recognizes that your stupid 'Center for\nPolicy Research' is nothing more than a fancy name for some bigot\nwho hates Israel."

In [41]:
X_train[0][10285]

"\nWales Conference, Adams Division, Semifinal\n\nI'm hoping for a Fuhr miracle, but I agree that Boston will likely win the\nseries.  Goaltending is about equal, top offensive players are about equal\n(Mogilny-LaFontaine vs. Oates-Juneau), but Buffalo has no answer to Neely\n(not to imply that Neely is not a top offensive player btw, in fact he's one\nof my favourites even though he's a damn Bruin :) ).  And the rest of the\nmatchup wrt lineup favours Boston anyway.  But I think it will go six.\n\n\nAgreed here...but Montreal will be pushed to the limit.  Is it just me, or\ndoes everything Montreal does in the playoffs come down to Roy?  Go Habs!!\n\nFinal\n\nI can't predict a Montreal victory because I've been watching them play for\n6 weeks and IMO they severly need some tougher players, especially to play\nin the Garden.  Last time they beat the B's 5-2 but Boston had a clear\nterritorial advantage; the victory was Roy's.  At the same time, I can't\nbring myself to predict the poss